name: group04-team04-env

channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
  - ipython
  - jupyter
  - ipykernel
  - hmmer
  - pytorch
  - cudatoolkit
  - networkx
  - pip
  - pip:
      - git+https://github.com/oxpig/SCALOP.git
      - fair-esm